name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java_version: [ '11' ]

    name: Run tests with Java ${{matrix.java_version}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK for Java ${{matrix.java_version}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java_version}}
          distribution: liberica
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build